### ISSUE TITLE
[질문] TestBase 클래스의 onBackPressed method override

### ISSUE THREAD

**Issue by c86j224s** [adodaorbit/GPMon#5]
TestBase 클래스의 onBackPressed method의 override 된 내용에

    overridePendingTransition(R.anim.move_left_in_activity, R.anim.move_right_out_activity);

와 같은 코드가 있는데, 어떤 의미인가요 ?  @_@

**Comment by adodaorbit** [comment]
복붙입니다.

**Comment by c86j224s** [comment]
넵 클로즈합니다
