### ISSUE TITLE
HourlyApiCallsActivity 에 특정 날짜를 하이라이팅해서 보는 기능이 필요합니다.

### ISSUE THREAD

**Issue by c86j224s** [adodaorbit/GPMon#7]
HourlyApiCallsActivity 에 특정 날짜 Line을 선택하면 
해당 날짜 Line의 하이라이팅이 toggle될 수 있었으면 합니다.

배경색도 좀 어울리지 않는 것 같습니다.

**Comment by adodaorbit** [comment]
필요없습니다.
